### ISSUE TITLE
Consider merging with https://github.com/jviotti/electron-json-storage

### ISSUE THREAD

**Issue by khullah** [Cocycles/electron-storage#3]
https://github.com/jviotti/electron-json-storage has a few more functionalities, like _has_, _keys_ and _clear_.

Both are great projects, though similar!

**Comment by thesbros** [comment]
No promises though, that's the killer for me.

**Comment by Good4m** [comment]
the other should just list deprecated and link to this one imo

**Comment by ran-y** [comment]
electron-json-storage tries to mimic the "localStorage" api, and therefor keeps the stored json files on one level, which enables methods like "keys".

I wanted an easy way to work with the storage and to design it the way i want. 

* Promises.
* subdirectories.

And in the future:
* not limit it to json only.
* encrypt the data.
