### ISSUE TITLE
isPathExists doesn't append .json on path

### ISSUE THREAD

**Issue by neonhomer** [Cocycles/electron-storage#4]
I noticed when trying to use `isPathExists`, it requires adding the `.json` to the path name unlike the `set` and `get` methods. I'm assuming that's on purpose but it doesn't seem consistent with the other methods.

Maybe that should be clarified in the README?

**Comment by ran-y** [comment]
Thanks @neonhomer !
I've change it in the README, let me know if it's clear enough now. d53c9e2d4454248da3fd919715b62bb9c91a70ad

**Comment by neonhomer** [comment]
Perfect! Thanks!
