### ISSUE TITLE
Support storing data outside the userData folder?

### ISSUE THREAD

**Issue by davej** [Cocycles/electron-storage#7]
Perhaps if `filePath` is an absolute user directory then it would just write to that folder. e.g..

```js
storage.get('/Users/dave/sites/my-site/config.json')
```

What do you think about this idea?

**Comment by davej** [comment]
I guess alternatively this could be abstracted as a separate module that `electron-storage` relies on. In this case electron-storage with simply process the paths and wrap the new abstracted module.

**Comment by ran-y** [comment]
The Limitation to "userData" directory, is for electron apps, which define this directory as the default for any operation system. As far as i know, you can use any storage management package for example - https://github.com/Cocycles/ya-storage.

Can you Tell me about your use case ?

**Comment by davej** [comment]
@ran-y That looks perfect, I guess I'm wondering why `electron-storage` doesn't include `ya-storage` as a dependency rather than duplicating most of the code?

**Comment by ran-y** [comment]
You are absolutely right.

**Comment by davej** [comment]
👍

**Comment by ran-y** [comment]
If you want to do a pull request with the suggested refactor it would be great :)

**Comment by davej** [comment]
Cool, is it as simple as I think it is or are there subtle differences between the libs?

**Comment by ran-y** [comment]
I think we should update ya-storage, but the changes are very subtle and will be discovered easily by the tests.
